### ISSUE TITLE
Add download stats to Readme

### ISSUE THREAD

**Issue by iampeterbanjo** [iampeterbanjo/vscode-elixir-linter#18]
As an extension developer I would like to encourage potential users to download this extension. Adding a download counter badge would be an evidence of social proof which can influence potential users.

The download counter badge should be the same value as the Visual Studio marketplace download stats displayed in VS Code.

**Comment by jeromechrist** [comment]
Hello !

Willing to take this one !

**Comment by iampeterbanjo** [comment]
Thank you @jeromechrist :-)
