### ISSUE TITLE
Configure running of .credo.exs file

### ISSUE THREAD

**Issue by hworld** [iampeterbanjo/vscode-elixir-linter#24]
Hey there, I'm trying to use your extension and it doesn't seem to be picking up my .credo.exs file for some reason.

When the extension runs it seems to do the default credo checks. When I run command line it shows all the warnings:
```
  Code Readability
┃
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/data_url_rewriter/signed.ex:1:11(DataUrlRewriter.Signed)

  Refactoring opportunities
┃
┃ [F] → Pipe chain should start with a raw value.
┃       lib/data_url_rewriter/signed.ex:12(DataUrlRewriter.Signed)
```

The extension only mentions the `@moduledoc` one, though. 

![screenshot from 2017-06-20 21-23-58](https://user-images.githubusercontent.com/1024321/27365728-d9568814-55fe-11e7-9554-773198732b07.png)

Is this maybe because it only shows a line and not the column? Or maybe it's not running in the project directory to pick up the config file?

**Comment by iampeterbanjo** [comment]
Thanks for feedback @hworld. 

What version are you using? I had initially built the extension to lint the files in memory without using the .credo.exs but that was kindly fixed by a contributor in `0.3.1`.

**Comment by hworld** [comment]
Hey there, I'm using 0.3.1 of the extension.
Credo: 0.8.1
Elixir: 1.4.4

**Comment by iampeterbanjo** [comment]
Hmm... could you comment with your .credo.exs file? And I'll do some tests with it.

**Comment by sido378** [comment]
I had the same experience after I changed the name of my credo config
```elixir
%{
  configs: [
    %{
      name: "foo",
      ...
    }
  ]
}

```
> Run any exec using `mix credo -C <name>`. If no exec name is given  "default" is used.

An option to define which config should be used in the extension settings would be great!

**Comment by iampeterbanjo** [comment]
@sido378 thanks for commenting. why do you rename the credo config file? do you have multiple projects? I'm just trying to understand your context.

**Comment by sido378** [comment]
I'm not renaming the credo file - I'm using multiple configurations within the same file.
For instance, one would be used by the CI to check if a PR satisfies the credo analysis, another would be used by the developer (e.g. if some checks should be shown to the developer, but not all of them should cause the build to fail).

```elixir
%{
  configs: [
    %{
      name: "default",
      ...
    },
    %{
      name: "build",
      ...
    }
  ]
}
```
Credo has the `-C` flag, that allows not to specify a different file, but a different config from the `configs` array within the `.credo` file

**Comment by iampeterbanjo** [comment]
thank you for the quick response @sido378 :-)
Would it be enough to have a VS Code elixirlinter setting for the config name to pass to the credo runner?

**Comment by sido378** [comment]
yes, that would be perfect 👍  🎉
