### ISSUE TITLE
Extension does not highlight a proper lines

### ISSUE THREAD

**Issue by konradkalita** [iampeterbanjo/vscode-elixir-linter#28]
Extension highlights whole file not the line with an error:
![bad_highlighting](https://user-images.githubusercontent.com/6229164/28997361-995a523a-7a12-11e7-8b10-21369e2e6412.png)

Expected highlighting:
![good_highlighting](https://user-images.githubusercontent.com/6229164/28997370-c73a5d62-7a12-11e7-8971-85d31c3a6f38.png)

**Comment by iampeterbanjo** [comment]
Published in 0.4.1
