### ISSUE TITLE
0.4.1 package broken somehow

### ISSUE THREAD

**Issue by ilkka** [iampeterbanjo/vscode-elixir-linter#31]
Trying to update to 0.4.1 or indeed uninstall and reinstall the extension, VS Code shows an error dialog saying "end of central directory record signature not found".

**Comment by iampeterbanjo** [comment]
Thanks for reporting this. I've tried on my Linux machine and it seems to be working as expected. I'll try on a Mac.

What OS are you running?

**Comment by ilkka** [comment]
Oh, sorry, left out that crucial info :( this was on a mac, and it happened in both the latest stable and the insiders version. I just tried it on the insiders version on my Windows machine and that worked fine.

**Comment by iampeterbanjo** [comment]
I'm running OS X El Capitan 10.11.6 and Visual Studio Code 1.15.0. I've uninstalled and reinstalled ElixirLinter without any issues. What versions do you have?

One way to see what might be going on is if you
1: Clone this repo
2: Open the folder of the cloned repo, vscode-elixir-linter, in Visual Studio Code
3: Press F5 - to run the extension in debug mode

Result - a new instance of Visual Studio Code should open with version 0.4.1 installed. In the original instance of VS Code you should see the output logs. Is there something in the logs that would point us to the root of the problem?

**Comment by ilkka** [comment]
Alright, turns out there was a broken cached file that caused this, I had to nuke my `~/Library/Application Support/Code` directory but that fixed it. Thanks for taking the trouble to help with this 👍

**Comment by iampeterbanjo** [comment]
No problem. I'm glad you were able to sort it out :-)
