### ISSUE TITLE
Inline highlighting/tooltip does not appear

### ISSUE THREAD

**Issue by amaisano** [iampeterbanjo/vscode-elixir-linter#36]
Using `credo` either version 0.8.4 or 0.8.10. I get the proper output in the **Problems** tab, but nothing at all appears in the editor in the code (this seemed to work before v. 0.8.4 for me).

![screen shot 2018-02-01 at 12 47 24 pm](https://user-images.githubusercontent.com/688435/35694053-13485e66-074e-11e8-931b-ef6cbe699efd.png)

**Comment by iampeterbanjo** [comment]
Hi @amaisano thanks for reporting this issue. I'll do some testing with credo 0.8.4 and get back to you. What version of VS code are you running?

**Comment by amaisano** [comment]
Version 1.19.3 (1.19.3)

**Comment by amaisano** [comment]
The very newest version of VSCode has the same problem - I still can't see the squiggly lines :(

**Comment by iampeterbanjo** [comment]
:(

**Comment by amaisano** [comment]
Not fixed in 1.21 either... could this be some kind of config issue? Are there vscode settings that govern on-screen markup elements like squiggly lines?

It's so strange. The hover/popup appears right where the squiggly red/green lines normally would:

<img width="1014" alt="screen shot 2018-03-16 at 5 12 42 pm" src="https://user-images.githubusercontent.com/688435/37544998-6dc502de-293d-11e8-8c77-d45a290b4084.png">

**Comment by iampeterbanjo** [comment]
Perhaps it's your theme getting in the way. Could you please try changing themes and let me know?

**Comment by iampeterbanjo** [comment]
Re: Are there vscode settings that govern on-screen markup elements like squiggly lines?
Not that I know of. I've checked my settings and I don't see any and I haven't defined any in the extension.

**Comment by iampeterbanjo** [comment]
@amaisano are you still having this issue?

**Comment by amaisano** [comment]
I finally sat down and debugged my settings. **I found the culprit:**

```json
    "files.exclude": {
        ...
        "**/deps": true,
        "deps": true,
        ...
    }
```

After removing those lines, the squiggly red and green marks came back (after restarting VS Code). I'm not 100% sure what this implies - we had those commented out to avoid seeing files related to our project.

**Comment by iampeterbanjo** [comment]
Awesome! glad you found a solution
