### ISSUE TITLE
Output All Credo Errors in VS Code

### ISSUE THREAD

**Issue by mthomps4** [iampeterbanjo/vscode-elixir-linter#38]
The list from `credo --strict` does not show in VS Code on load or run.
Linting errors only appear AFTER opening the file and ONLY for that file.

I still have to run the credo command and find each individual file.
It would be helpful for the list of files & errors to show up in the problems view on run/load.

**Comment by iampeterbanjo** [comment]
Thanks for the feedback. Yes, it would be great to see all the errors in the problem view.

It looks like you're [not the only one](https://github.com/Microsoft/vscode/issues/13953) asking for this. From my understanding, this seems to be feature [best served](https://github.com/tomv564/LSP/issues/233) with the Elixir language server. The work around seems to be to create [a task runner](https://github.com/Microsoft/vscode/issues/13953#issuecomment-366306884) that is run on project load/run. 

Does that make sense to you?

**Comment by mthomps4** [comment]
Thanks for the links... I'll see if I can configure a task runner in the mean time.

**Comment by iampeterbanjo** [comment]
The more I think about it, the more I like this suggestion. I've been working on some React JS and the Flow type checker lints all the files in the project and I like it :)

**Comment by iampeterbanjo** [comment]
See #10
