### ISSUE TITLE
Can we add auto-fix support?

### ISSUE THREAD

**Issue by silviurosu** [iampeterbanjo/vscode-elixir-linter#87]
There are many warnings that would be easy to auto-fix like for example aliases are not alphabetically sorted.
For example ESLint has this functionality
Can we have that in the linter?

**Comment by iampeterbanjo** [comment]
Hmm... the main goal of this extension is to create an interface to receive [credo](https://github.com/rrrene/credo) output in VS Code.

I do like ESLint's autofix and Haskell (which was the inspiration for this extension) has this ability - to autofix code. I'm hoping to have some time to do a rewrite of this extension that will make suggestions like yours easier to implement.

Do you have any examples of working code that I could use for this autofix feature?
